### ISSUE TITLE
Problem with 3rd party cookies...

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/CountDownDevFest2018#18]
Unable to start in localhost using Twitter:
`http://localhost:8080/#/auth`
<img width="946" alt="capture d ecran 2018-10-14 a 22 24 47" src="https://user-images.githubusercontent.com/525974/46921799-196dbe00-d000-11e8-9745-bbb8e4e3dabd.png">

Or with google using `galaxy.gdgnantes.com`
https://galaxy.gdgnantes.com/#/auth
<img width="965" alt="capture d ecran 2018-10-14 a 22 27 26" src="https://user-images.githubusercontent.com/525974/46921833-5934a580-d000-11e8-856f-678d61f8411e.png">

**Comment by jlandure** [comment]
A tester et à configurer sur les autres auth providers :)

**Comment by jefBinomed** [comment]
Twitter & Github can't be configure to use multiple urls for one application. So to test Twitter & Github, you have to to it on galaxy.gdgnantes.com.

**Comment by jlandure** [comment]
Ok. It works with google auth
Why not? It's the "main" domain isn't it?

**Comment by jefBinomed** [comment]
Yep, it's the main domain, but localhost is not configure for twitter, github, facebook. I'll check every third party login to see if everything works

**Comment by jefBinomed** [comment]
I fix the configs issues, and test it with 4 providers. It works on galaxy.gdgnantes.com
